$messages = @(
    "chore: Initial repository setup",
    "feat: Add design system tokens and basic CSS variables",
    "feat: Create basic HTML skeleton for landing page",
    "feat: Implement glassmorphism navbar",
    "feat: Add hero section with primary CTA",
    "style: Set up Plus Jakarta Sans typography",
    "feat: Add secondary glow effects to hero section",
    "feat: Implement problem section with feature cards",
    "feat: Add stats bar with count-up animation",
    "feat: Create multi-channel payment feature list",
    "style: Refine button hover and glow states",
    "feat: Add 'How It Works' section with timeline",
    "feat: Implement safety and security section",
    "feat: Create detailed feature pillars with icons",
    "feat: Add 'Who It's For' segment with personas",
    "feat: Implement waitlist form and success state",
    "feat: Add responsive footer with social links",
    "feat: Create About Us page structure",
    "feat: Add mission and values to About page",
    "feat: Create How It Works details page",
    "feat: Implement detailed channel resilience breakdown",
    "feat: Create Contact Us page with FAQ",
    "feat: Add contact form with validation",
    "feat: Implement smooth scroll behavior",
    "feat: Add intersection observer for reveal animations",
    "feat: Create initial SVG animations for brand logo",
    "fix: Navbar visibility on dark backgrounds",
    "style: Improve mobile menu UX and transitions",
    "feat: Implementation of the particle mesh background",
    "perf: Optimize particle canvas rendering",
    "feat: Add custom preloader with brand elements",
    "style: Enhance preloader mesh gradient",
    "feat: Add progress counter to preloader",
    "feat: Implement logo drawing animation in loader",
    "fix: Logo centering on smaller mobile screens",
    "style: Add glass disk effect to preloader logo",
    "feat: Add UPI 123 method to failed alternatives list",
    "feat: Implement mobile hero floating shapes",
    "feat: Add morphing animation to background shapes",
    "feat: Implement oscillating animation for hero badge",
    "feat: Add shifting gradient effect to hero text",
    "style: Refine mobile-specific typography scales",
    "fix: Hamburger menu active states and backdrop blur",
    "chore: Update brand identity to OneBar.in",
    "fix: Ensure brand name consistency in preloader",
    "fix: Update footer copyright to include .in extension",
    "chore: Final brand consistency check across all pages",
    "feat: Add proprietary LICENSE file",
    "style: Final polish of hero reveal animations",
    "chore: Production build optimization",
    "docs: Update README and documentation",
    "chore: Ready for deployment to OneBar.in"
)

git add .
foreach ($msg in $messages) {
    # We commit one by one. In a real scenario we'd commit changes over time.
    # To simulate history, we'll use --allow-empty if needed, 
    # but here we'll just commit these messages sequentially.
    git commit --allow-empty -m "$msg"
}
